### ISSUE TITLE
Hello, is there any way to set cookis while palying a http stream.

### ISSUE THREAD

**Issue by lyzzbhoneyline** [af913337456/IjkPlayerDemo#1]
How to paly a http stream video with cookies, some url need cookies, pls do me a favor, tnks. :D

**Comment by af913337456** [comment]
I've met this problem before,you can take a look at my other project,which can play video cache without network connection,here is the url :
https://github.com/af913337456/LGHVideoPlayer , this may solve your problem,by the way, which country do you belong to?

**Comment by lyzzbhoneyline** [comment]
Nice demo from u,thks for ur reply,I'm coming from UA, I'v got another question from ur IjkPlayerDemo object, why not display the progress bar in full screen mode?

**Comment by af913337456** [comment]
I remeber it can show the progress bar in full screen mode,and it work for my phone demo until now.

**Comment by af913337456** [comment]
My code comment is written in Chinese, it may be difficult to you.

**Comment by lyzzbhoneyline** [comment]
Alright, thks for ur patience, I'll take sometime to study ur code.:D
